sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: nX26x8+iiaE3kyI5cpYtJoKVrXK1LDSs8rgDAwaKJIj0ybOnUjoLC5o/mbFZVYSEY1hAbL1X0nd8475RJWmGqRMaf19gQ2OpXFb8VeSVoqkUUIjug1MYzW3dGFW84neN9+0UCkUsVMdMUeUFjyV83+e/OS4JJJ6xXnoJ3Z5u818V0e4NyxN00TfLU960VM2lZgXVJcXXS1Ww+9vRdDGdPG2wzV+cD7SC4QLUeivrSeQEefa6SEO5MwsDQunbv/wLK0J03kN9OKpZRAJI4qWNRRWoC3eFRdAhe1QPbin2Ksac5MxaQTDi72Ez7qiaCGuAhpV4P50ddEkmOnBxFocVI1SYbGYMgS4guzl42ImSec2NeKA/udRe5vItt0M1IZYNVBpcS29WaxEgvk9dWxkxKWrkTOYPOaS8NhOb9Qb6mcHz95XNecTol204fzrnopiG9IcBKcvemHJlkRu1gVDbEn4FdrhVzTc/Sn1Ql7HqxWaESa00YGbfQVOFWaxoP0ssc0d1M+GmFPBKlol1i7x3VFmu53CQ7ZXbv09oitnFoZwp421bAET32xanyvZMekvkINrhfxrM5pnDM9cAcru8a0Mij04EtjFMdB/y3J166Y6YAlcfg8KEV3B34cIqq0ioQIgH6MtYuzB6Ne21Fd8CvehRTHxz5E/LDIU0qfEE1Pc=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Theologico-Political-Treatise-Part-2_990
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy